### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by pyontarou** [pyontarou/furima-34478#9]
自身のフリマアプリのURL:https://furima-34478.herokuapp.com/

Basic認証のIDとパスワード:  ID = admin   パスワード = 9317

出品者用のメールアドレスとパスワード:
メールアドレス:aa@a.com
パスワード:q1w2e3r4

購入者用のメールアドレスとパスワード
メールアドレス:nyan@nyan.com
パスワード:q1w2e3r4

**Comment by mo1015** [comment]
ご提出ありがとうございます！
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね！
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております。

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/62644781/108613021-0de0fc00-7431-11eb-9fa6-8fac162b90dd.png)
